# -----------------------------------------------------
# | Supported databases: MariaDB & MySQL
# -----------------------------------------------------
database:
  url: jdbc:mariadb://address:3306/
  dbname: warps
  username: warps-bukkit
  password: amazing-password
  max-lifetime: 1800000 # 30 minutes
  connection-timeout: 30000 # 30 seconds
  keepalive-time: 120000 # 2 minutes
  maximum-pool-size: 10 # Maximum number of connections in the pool

config-version: 1.0